---
- hosts: localhost 
  become: yes
  vars_files:
    - roles/application_installation/vars/apps.yml 
    - vars/users.yml
  tasks:
    - name: Desktop 
      include_role:
        name: desktop
      loop: "{{ users }}"
      loop_control:
        loop_var: user_name
  roles:
    - application_installation
    - ssh
    - firewall
    - desktop_look
