---
- hosts: all
  become: true
  pre_tasks:
    - name: Update package cache (arch)
      ansible.builtin.pacman: update_cache=yes
      changed_when: False
      when: ansible_distribution == "Archlinux"

    - name: Update package cache (debian, etc)
      ansible.builtin.apt: update_cache=yes
      changed_when: False
      when: ansible_distribution in ["Debian", "Ubuntu"]

  vars_files:
    - roles/application_installation/vars/apps.yml 
    - vars/users.yml
    - vars/ports.yml
  tasks:
    - name: Desktop Look
      include_role:
        name: desktop_look
      loop: "{{ users }}"
      loop_control:
        loop_var: user_name
  roles:
    - users
    - application_installation
    - ssh
    - firewall
    - desktop

- hosts: all
  become: true
  tasks: 
    - name: Cleanup package cache (debian and ubuntu)
      ansible.builtin.apt:
        autoremove: yes
        purge: yes
      when: ansible_distribution in ["Debian", "Pop!_OS", "Ubuntu"]
