---
- name: Install syncthing apt if not present in system
  ansible.builtin.apt:
    name: syncthing
    state: latest
    update_cache: yes

- name: Install lxml via pip if not present in system
  ansible.builtin.pip:
    name: lxml
    state: latest

- name: Start syncthing service to get configuration files for each user
  ansible.builtin.systemd:
    name: syncting@{{ item.user }}
    state: started
  loop:
    {{ users_for_syncthing }}

# add check if service started before stop that service

- name: Stop syncthing service to set configuration for each user
  ansible.builtin.systemd:
    name: syncting@{{ item.user }}
    state: stopped
  loop:
    {{ users_for_syncthing }}

- name: Update syncthing user configuration file for each user
  community.general.xml:
    path: "/home/{{ item.user }}/.config/syncthing/config.xml"
    xpath: "{{ item.xpath }}"
    value: "{{ item.value }}"
  loop:
    {{ configuration_syncthing_for_<user> }}

- name: Final start of syncthing service and enabled 
  ansible.builtin.systemd:
    name: syncthing@{{ item.user }}
    state: started
    enabled: yes

