- name: Enable UFW firewall
  ansible.builtin.ufw:
    state: enabled
    default: deny
    direction: incoming

- name: Allow outgoing traffic
  ansible.builtin.ufw:
    rule: allow
    direction: outgoing

- name: Allow SSH through the firewall
  ansible.builtin.ufw:
    rule: allow
    name: OpenSSH

