- name: Enable UFW firewall
  ansible.builtin.ufw:
    state: enabled
    default: deny
    direction: in

- name: Allow outgoing traffic
  ansible.builtin.ufw:
    rule: allow
    direction: out

- name: Allow SSH through the firewall
  ansible.builtin.ufw:
    rule: allow
    name: OpenSSH

