- name: Update apt cache
  ansible.builtin.apt:
    update_cache: yes

- name: Upgrade all packages
  ansible.builtin.apt:
    upgrade: dist

- name: Install application list
  ansible.builtin.package:
    name: "{{ item }}"
    state: present
  loop: "{{ app_list }}"
