- name: Update and upgrade system
  ansible.builtin.apt:
    update_cache: yes
    upgrade: dist

- name: Install application list
  ansible.builtin.package:
    name: "{{ item }}"
    state: present
  loop: "{{ app_list }}"

- name: Clean up
  ansible.builtin.apt:
    state: absent
    autoremove: yes
    autoclean: yes
