---
- name: Set custom keybindings for user {{ user_name }}
  become: yes
  become_user: "{{ user_name }}"
  environment: 
  XDG_RUNTIME_DIR: "/run/user/{{ lookup('ansible.builtin.pipe', 'id -u ' + user_name) }}"
  include_tasks: keybingings.yml
  loop:
    - { id: "0", binding: "<Mod4>p", name: "Software Manager", action: "mintinstall" }
    - { id: "1", binding: "<Mod4>v", name: "Virtual Manager", action: "virt-manager" }
    - { id: "2", binding: "<Mod4>g", name: "Steam", action: "sh -c 'STEAM_FRAME_FORCE_CLOSE=1 steam %U'" }
    - { id: "3", binding: "<Mod4>t", name: "Terminal", action: "mate-terminal" }

- name: 
  community.general.dconf:
    key: "/org/mate/desktop/peripherals/keyboard/numlock-state"
    value: "'on'"
    state: present

